### ISSUE TITLE
[bug] I find a bug here

### ISSUE THREAD

**Issue by smileboywtu** [anrosent/LT-code#2]
I read this code as needed, and I find there is small bug here, on my computer I can't get the right data.
after several hours hard work. I find the byte order isn't pair here.

you have read the data from the file use the sys.byteorder, but when you finish get out all the block in the 
decode process, you just use the big as the byteorder not the sys.byteorder, it will cause some bug on several computer.

**Comment by anrosent** [comment]
fixed in 69476fdcc3c2a49c2d8baac9fd44c29e785afa69, thanks!
