### ISSUE TITLE
API for parsing a block from bytes, not just stream of blocks from file-like

### ISSUE THREAD

**Issue by anrosent** [anrosent/LT-code#4]
Support single block parsing from **bytes**, not just parsing stream of blocks from a file-like

**Comment by smileboywtu** [comment]
good idea, some times the data is so large or not prepared, it need to encrypt some parts of the message, so just encrypt the bytes is more generic way

**Comment by anrosent** [comment]
added non-validated _block_from_bytes_ method to public decoder API.
